# Generated by Django 5.2.8 on 2025-11-23 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_rename_is_active_match_is_completed_ball_innings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bat_style',
            field=models.CharField(choices=[('right', 'Right Hand Batsman'), ('left', 'Left Hand Batsman')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='bowl_style',
            field=models.CharField(choices=[('right', 'Right Arm Bowler'), ('left', 'Left Arm Bowler'), ('none', 'Not a Bowler')], default='right', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket.team'),
        ),
    ]
